name: Check Unit Test In Progress 2

on:
  pull_request:
    branches:
      - develop

jobs:
  check-unit-test-progress:
    if: ${{ vars.DISABLE_UNIT_TEST_CHECK != 'true' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Get current date
        id: get_date
        run: |
          export DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo $DATE
          echo "Date=$DATE"
          echo "date=$DATE" >> $GITHUB_OUTPUT
